# Generated by Django 4.1.3 on 2022-12-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_wishes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishes',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
